name: food_delivery
description: "A Flutter food delivery application."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.10.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  google_fonts: ^6.3.3
  cherry_toast: ^1.13.0
  readmore: ^3.0.0

  # State management & backend
  flutter_riverpod: ^3.0.3
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/food_delivery/
    - images/food_delivery/product/
    - images/food_delivery/icon/
    - .env

  # Uncomment and customize fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
